// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM9HeB18C_DZOD8kJ0ULskZOAItGvosmQ',
    appId: '1:695277581981:web:2d2c4aeac20f508c50c674',
    messagingSenderId: '695277581981',
    projectId: 'ecommerceapp-94be4',
    authDomain: 'ecommerceapp-94be4.firebaseapp.com',
    storageBucket: 'ecommerceapp-94be4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2ZqlDMEEaMVl-voWrtWU8BGtJLzLn3j4',
    appId: '1:695277581981:android:5daa0e3b35138e2350c674',
    messagingSenderId: '695277581981',
    projectId: 'ecommerceapp-94be4',
    storageBucket: 'ecommerceapp-94be4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2U5oq27mOxKIFcgr6_khbPlC2K_NIBhM',
    appId: '1:695277581981:ios:d16ccc3f6a04864250c674',
    messagingSenderId: '695277581981',
    projectId: 'ecommerceapp-94be4',
    storageBucket: 'ecommerceapp-94be4.appspot.com',
    androidClientId: '695277581981-rjae61dv5hksjvfohgt25900n6gov9fq.apps.googleusercontent.com',
    iosClientId: '695277581981-v3ectmo4iba49vqjetgvv27eulohpiap.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2U5oq27mOxKIFcgr6_khbPlC2K_NIBhM',
    appId: '1:695277581981:ios:d16ccc3f6a04864250c674',
    messagingSenderId: '695277581981',
    projectId: 'ecommerceapp-94be4',
    storageBucket: 'ecommerceapp-94be4.appspot.com',
    androidClientId: '695277581981-rjae61dv5hksjvfohgt25900n6gov9fq.apps.googleusercontent.com',
    iosClientId: '695277581981-v3ectmo4iba49vqjetgvv27eulohpiap.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM9HeB18C_DZOD8kJ0ULskZOAItGvosmQ',
    appId: '1:695277581981:web:27248d3611b4556a50c674',
    messagingSenderId: '695277581981',
    projectId: 'ecommerceapp-94be4',
    authDomain: 'ecommerceapp-94be4.firebaseapp.com',
    storageBucket: 'ecommerceapp-94be4.appspot.com',
  );

}